print("----Registrar datos personales----")
name = input("Ingrese su nombre completo: ")
name = input("Ingrese su nombre completo: ")
name = input("Ingrese su nombre completo: ")
name = input("Ingrese su nombre completo: ")